### ISSUE TITLE
error when loading data

### ISSUE THREAD

**Issue by leao1995** [hansen7/OcCo#11]
Hi,

I'm trying to load the lmdb data you shared using the lmdb_dataflow function, but I got an error:

_pickle.UnpicklingError: invalid load key, '\xdc'.

Do you know how to fix this? Thanks

**Comment by hansen7** [comment]
Thanks for your interest in our work and data!

For the environments I’m using, please see:

https://github.com/hansen7/OcCo/blob/c218a2bb446f91702cf8fa6f56bb3a1da406009f/OcCo_Torch/Requirements_Torch.txt#L1-L14

and relavant codes for I/O:

https://github.com/hansen7/OcCo/blob/c218a2bb446f91702cf8fa6f56bb3a1da406009f/OcCo_Torch/train_completion.py#L70-L71

https://github.com/hansen7/OcCo/blob/c218a2bb446f91702cf8fa6f56bb3a1da406009f/OcCo_Torch/utils/LMDB_DataFlow.py#L75-L89

I’ve just downloaded the data from the Google Drive and test these myself, so it should works fine, as reproduced by others (#8) as well.

**Comment by hansen7** [comment]
BTW, if you want to convert the `lmdb` files into other format, e.g., `h5`, you might find `OcCo_Torch/utils/lmdb2hdf5.py` useful

**Comment by DerekHodder** [comment]
For anyone else stumbling across this issue, make sure you're using the right version of `tensorpack`. I had this exact problem with the exact same "invalid load key" in the TF implementation of OcCo. Although the `Requirements_TF.txt` allows any version >=0.8.9, what worked for me was downgrading from `tensorpack=0.11` (the only version available through conda) to `tensorpack=0.8.9`.
