### ISSUE TITLE
Can't reproduce Linear SVM result with DGCNN backbone.

### ISSUE THREAD

**Issue by JasonNie96** [hansen7/OcCo#21]
Hi Hansen,

Thanks for your work!

I'm trying to reproduce your result in Table 10. It said with the DGCNN backbone, OcCo has 89.2% accuracy. But I loaded your pre-trained model: dgcnn_occo_cls.pth and train the svm with the following command:

```
python train_svm.py --gpu=0 --model=dgcnn_util --dataset=modelnet40 --restore_path=./data/pretrained/dgcnn_occo_cls.pth.
```

But it only gets 88.4% accuracy. May I ask did I do anything wrong?

**Comment by hansen7** [comment]
Hi, @JasonNie96 . Thanks for asking. 

The provided checkpoints are mainly for classification tasks (with MLP output heads), for the results reported in the appendix, I have rerun the pre-training with different configurations many times, and reported the best results I have in hand.
