### ISSUE TITLE
Experiment setting of fine-tuning on ModelNet40

### ISSUE THREAD

**Issue by SimingYan** [hansen7/OcCo#22]
Hi Hansen,

Thanks for your great work. I have one quick question here.

May I ask what's the detailed experiment setting of fine-tuning on ModelNet40? Could you please provide the command of this task?

Now I'm using:
```
python train_cls.py --model=dgcnn_cls --dataset=modelnet40 --log_dir=dgcnn_occo --num_point=2048 --restore --restore_path=./path/to/dgcnn_occ_cls.pth
```

If I made any mistakes, please let me know! Thank you!

**Comment by hansen7** [comment]
Hi @SimingYan . Thanks for your interest, it is the same setting as we trained on ScanObjectNN (in readme file)

**Comment by SimingYan** [comment]
Got it. Thanks for the clarification.
