### ISSUE TITLE
two types of pre-trained weights

### ISSUE THREAD

**Issue by zshyang** [hansen7/OcCo#28]
Hi @hansen7 
I saw you have released two types of weights. They are *_cls.pth and *_seg.pth. My guess is that they have the same encoder but just the seg one has a randomly initialized segmentation network appended to the pre-trained encoder. 
Not sure if my guess is correct or not so need your information.
Best regards.

**Comment by hansen7** [comment]
Hi @zshyang, it is :)

**Comment by zshyang** [comment]
Hi @hansen7 , 
thanks for the reply. I am still curious about why do you have such an implementation. Why do not just save the *_cls.pth and load it to the encoder part in the segmentation tasks.

**Comment by hansen7** [comment]
Oh, the encoders are slightly different, for classification and segmentation. You can check the original papers and codes :)

**Comment by zshyang** [comment]
thanks!
