### ISSUE TITLE
How about SensatUrban

### ISSUE THREAD

**Issue by zshyang** [hansen7/OcCo#29]
Hi @hansen7 
I did not see SensatUrban in your implementation of data setting 
https://github.com/hansen7/OcCo/blob/master/OcCo_Torch/data/readme.md
Best regards

**Comment by hansen7** [comment]
I am following the same preprocessing procedure in the PointNet and DGCNN. I've asked @QingyongHu to prepare the data in such format. :)

**Comment by zshyang** [comment]
thanks.
