### ISSUE TITLE
dataset for OcCo training 

### ISSUE THREAD

**Issue by cxlcl** [hansen7/OcCo#6]
Hi, 

Would you please provide the occluded point cloud data used in the training for the completion task (train_completion.py)? I was looking for it based on the documentation [here](https://github.com/hansen7/OcCo/tree/master/OcCo_Torch/data) but in no vain. 

Thanks!
Chao

**Comment by hansen7** [comment]
Hi @cxlcl, please see it here:

- [OcCo dataset](https://drive.google.com/drive/folders/1gXNcARYxAh8I4UskbDprJ5fkbDSKPAsH?usp=sharing)

The following is just for self-references on `gdrive` (to upload/download files to google drive via command lines):
- [Github issues](https://github.com/prasmussen/gdrive/issues/533)
- [Create an app to fix the authentication](https://www.mynotepaper.com/mount-google-drive-using-gdrive-on-linux-server-with-own-oauth-credentials)

**Comment by cxlcl** [comment]
Thank you. 
This is really helpful !
